# -*- coding: utf-8 -*-
"""students.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YzoJMFR2yRqkffmCEXcr0SOOonibLLIx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/student_data.csv")
df

df.info()

df.describe().sum()

df.duplicated().sum()

df.columns=df.columns.str.title()
df

df.isnull().sum()

#histplot
sns.histplot(data=df,x="Health",bins=5,kde=True,color="blue")
plt.title("student health")
plt.xlabel("Health")
plt.show()

#boxplot
sns.boxplot(data=df,x="Health",y="Age",color="yellow")
plt.show()

sns.barplot(data=df,x="Health",y="Age",color="orange")
plt.show()

sns.lineplot(data=df,x="Health",y="Age",color="red")
plt.show()

sns.scatterplot(data=df,x="Health",y="Age",color="violet")
plt.show()

sns.barplot(data=df,x="Health",y="Age",hue="Sex",palette="Set1")
plt.title("Age across health")
plt.show()

sns.pairplot(data=df,vars=["Health","Age"],hue="Sex",palette="Set1")
plt.show()

corr=df[["Health","Age"]].corr()
print(corr)

sns.heatmap(corr,annot=True,cmap="coolwarm")
plt.show()